// appData.js — Verified NGO, Orphanage, Old Age Home & Volunteer Activity Data for Chandigarh Tricity & Punjab
// Real coordinates (lat, lng) enable live real-time distance calculation from user's current location.

export const ngos = [
  {
    id: 1,
    name: 'Tammana NGO',
    category: 'ngo',
    description: 'A prominent Chandigarh social welfare NGO championing child education, women empowerment, slum community upliftment, and extensive winter clothing and ration distribution across Chandigarh.',
    address: 'House No. 3432, Sector 38-D (Drives across Sectors 17, 25, 38 & Dhanas)',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7471,
    lng: 76.7441,
    verified: true,
    contactEmail: 'contact@tammana.org.in',
    contactPhone: '+91 96460 72207',
    website: 'https://www.tammana.org.in',
    founded: '2008',
    urgentNeeds: ['Warm Woollen Sweaters & Jackets', 'School Stationery & Notebooks', 'Dry Rations & Pulses'],
    beneficiariesServed: '12,000+ Children & Families',
    operatingHours: '9:00 AM - 7:00 PM (Mon - Sat)',
    verificationDetails: 'Reg. No. 4410 under Societies Act, 80G Tax Exemption Certified',
    impactHighlights: 'Organised over 150 community donation drives and actively educates 250+ underprivileged children in Chandigarh.'
  },
  {
    id: 2,
    name: 'Bal Niketan Children Home',
    category: 'orphanage',
    description: 'Established in 1983 by educationist late Shri J.D. Sharma, Bal Niketan is a certified residential home for orphaned, destitute, and abandoned children, providing emotional care, schooling, and vocational life training.',
    address: 'Sector 2 (Near Mansa Devi Complex link)',
    city: 'Panchkula',
    state: 'Haryana (Chandigarh Tricity)',
    lat: 30.6942,
    lng: 76.8606,
    verified: true,
    contactEmail: 'contact@balniketan.org',
    contactPhone: '+91 172 2560780',
    website: 'https://balniketanchd.com',
    founded: '1983',
    urgentNeeds: ['School Uniforms & Shoes', 'Nutritional Health Drinks & Milk Powder', 'Children Story & Activity Books'],
    beneficiariesServed: '60 Resident Children',
    operatingHours: '9:00 AM - 6:00 PM (Everyday)',
    verificationDetails: 'Child Welfare Committee Registered, 80G Certified Non-Profit',
    impactHighlights: '100% formal school enrollment with ongoing digital literacy and creative arts mentorship.'
  },
  {
    id: 3,
    name: 'Sri Guru Granth Sahib Sewa Society (Tera Hi Tera)',
    category: 'ngo',
    description: 'Renowned charitable mission across the Tricity providing the famous ₹13 medicine program, free cataract surgeries at Guru Ka Langar Eye Hospital, and daily hot nutritious langar food for patients outside Chandigarh hospitals.',
    address: 'Sector 45-B (Charitable Super-Specialty Hospital) & Sector 18',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7077,
    lng: 76.7656,
    verified: true,
    contactEmail: 'sewa@terahitera.org',
    contactPhone: '+91 172 2602113',
    website: 'https://terahitera.org',
    founded: '1997',
    urgentNeeds: ['Prescription & Essential OTC Medicines', 'Wheat Flour (Atta) & Basmati Rice', 'Adult Hygiene & Dressing Kits'],
    beneficiariesServed: '45,000+ Patients Annually',
    operatingHours: '8:00 AM - 8:00 PM (Everyday)',
    verificationDetails: 'Registered Charitable Society #248, 80G & 12A Certified, Verified 2026',
    impactHighlights: 'Performed over 8,500 free eye surgeries and serves thousands of free hot meals daily at PGI and GMCH 32.'
  },
  {
    id: 4,
    name: 'Lions Club Old Age Home',
    category: 'oldAgeHome',
    description: 'Managed by Lions Club Central Chandigarh, providing peaceful shelter, 24-hour nursing care, nutritious hot meals, and compassionate medical attention for senior citizens without family support.',
    address: 'Sector 15-D',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7512,
    lng: 76.7667,
    verified: true,
    contactEmail: 'lionseldercare.chd@gmail.com',
    contactPhone: '+91 172 2784610',
    website: 'https://chandigarhonline.in',
    founded: '1985',
    urgentNeeds: ['Adult Diapers & Underpads', 'Wheelchairs & Walking Sticks', 'Thermal Blankets & Bedding'],
    beneficiariesServed: '50 Senior Residents',
    operatingHours: '24 Hours Operational (Visitor Hours: 10 AM - 6 PM)',
    verificationDetails: 'Lions International Charter 15-D, Senior Welfare Registered',
    impactHighlights: 'Continuous geriatric doctor visits, physiotherapy sessions, and festive family celebrations for elder residents.'
  },
  {
    id: 5,
    name: 'Nanhi Jaan (Veeranwali Foundation)',
    category: 'ngo',
    description: 'Dedicated to saving critically ill and underprivileged infants and children by providing life-saving pediatric medical equipment, essential medicines, and critical care consumables at PGIMER Chandigarh.',
    address: 'SCO 343-345, Sector 34-A',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7242,
    lng: 76.7681,
    verified: true,
    contactEmail: 'helpdesk@nanhijaan.in',
    contactPhone: '+91 85580 50000',
    website: 'https://nanhijaan.com',
    founded: '2010',
    urgentNeeds: ['Pediatric First-Aid & Medicines', 'Infant Care Supplies & Baby Diapers', 'Educational Toys & Art Drawing Books'],
    beneficiariesServed: '18,000+ Children Treated',
    operatingHours: '9:30 AM - 6:30 PM (Mon - Sat)',
    verificationDetails: 'FCRA Registered, 80G Certified, Official Medical Partner with PGIMER Child Health',
    impactHighlights: 'Equipped government child ICU units with ventilators, phototherapy units, and emergency medication.'
  },
  {
    id: 6,
    name: 'Gur Aasra Trust',
    category: 'orphanage',
    description: 'A loving sanctuary caring for destitute, orphaned, and single-parent children in the Tricity, providing English medium education, nutritional care, computer training, and holistic rehabilitation.',
    address: 'Village Palsora, Sector 55 (Near Mohali Border)',
    city: 'Mohali',
    state: 'Punjab',
    lat: 30.7225,
    lng: 76.7320,
    verified: true,
    contactEmail: 'guraasratrust@gmail.com',
    contactPhone: '+91 98140 16598',
    website: 'https://localpunjab.com',
    founded: '2000',
    urgentNeeds: ['CBSE Class 1-12 Textbooks', 'Winter Sweaters & Tracksuits', 'Grocery Kits (Pulses, Cooking Oil & Grains)'],
    beneficiariesServed: '70 Resident Children',
    operatingHours: '8:00 AM - 7:30 PM (Everyday)',
    verificationDetails: 'Punjab Child Protection Society Recognized, 80G Audited',
    impactHighlights: 'Fully supports residential education, computer literacy, and sports training for over 70 destitute children.'
  },
  {
    id: 7,
    name: 'Robin Hood Army (Chandigarh Tricity Chapter)',
    category: 'ngo',
    description: 'A zero-funds volunteer organization bridging surplus food from Tricity restaurants and sweetshops to hungry families across Dhanas, Maloya, Mauli Jagran, and Industrial Area settlements.',
    address: 'Sector 17 Plaza & Madhya Marg (Hub)',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7398,
    lng: 76.7827,
    verified: true,
    contactEmail: 'chandigarh@robinhoodarmy.com',
    contactPhone: '+91 98722 34510',
    website: 'https://robinhoodarmy.com',
    founded: '2014',
    urgentNeeds: ['Cooked Fresh Meals & Bread', 'Packaged Dry Food Grains', 'Insulated Clean Food Boxes'],
    beneficiariesServed: '60,000+ Meals Distributed',
    operatingHours: '7:00 AM - 10:30 PM (Everyday)',
    verificationDetails: 'Zero-Funds Volunteer Movement, Community Audited 2026',
    impactHighlights: 'Mobilises 400+ student and professional volunteers conducting weekly night food drives and Robin Academy teaching.'
  },
  {
    id: 8,
    name: 'Senior Citizens Council Old Age Home',
    category: 'oldAgeHome',
    description: 'A community-run elder care home providing assisted living, doctor consultations, clean rooms, healthy meals, and library facilities for senior citizens seeking dignity and peace in the Tricity.',
    address: 'Sector 15',
    city: 'Panchkula',
    state: 'Haryana (Chandigarh Tricity)',
    lat: 30.6820,
    lng: 76.8480,
    verified: true,
    contactEmail: 'sccpanchkula@gmail.com',
    contactPhone: '+91 172 2574920',
    website: 'https://panchkulaonline.in',
    founded: '1994',
    urgentNeeds: ['Blood Pressure & Glucometer Strips', 'Orthopedic Bedding & Pillows', 'Daily Personal Hygiene Kits'],
    beneficiariesServed: '45 Senior Citizens',
    operatingHours: '24 Hours Operational',
    verificationDetails: 'Haryana Social Welfare & Empowerment Department Recognized',
    impactHighlights: 'Organises weekly geriatric doctor checkups, physiotherapy camps, and intergenerational storytelling sessions.'
  },
  {
    id: 9,
    name: 'Indian Red Cross Society (Punjab State Branch)',
    category: 'ngo',
    description: 'Apex humanitarian organization providing statewide emergency disaster relief, subsidized generic medicines, blood bank services, patient transport, and disability aids across Punjab and Chandigarh.',
    address: 'Red Cross Bhawan, Adjoining Rose Garden, Madhya Marg, Sector 16',
    city: 'Chandigarh',
    state: 'Punjab / Chandigarh',
    lat: 30.7483,
    lng: 76.7821,
    verified: true,
    contactEmail: 'punjabredcross_16@rediffmail.com',
    contactPhone: '+91 172 2542180',
    website: 'http://www.punjabredcross.com',
    founded: '1920',
    urgentNeeds: ['First Aid & Emergency Bandages', 'Packaged Clean Drinking Water', 'Wheelchairs & Walking Crutches'],
    beneficiariesServed: '100,000+ Citizens in Punjab & Tricity',
    operatingHours: '9:00 AM - 5:30 PM (Mon - Sat)',
    verificationDetails: 'Statutory Body under Indian Red Cross Act, 80G Certified',
    impactHighlights: 'Coordinates regional disaster responses, voluntary blood donation networks, and vocational rehabilitation.'
  },
  {
    id: 10,
    name: 'Jyoti Sarup Kanya Asra Society',
    category: 'orphanage',
    description: 'Dedicated residential home and shelter offering schooling, higher education sponsorships, and career skills to destitute girls, orphans, and young women from Punjab.',
    address: 'Garden Colony, Near Kharar Bus Stand, Kharar',
    city: 'Mohali',
    state: 'Punjab',
    lat: 30.7450,
    lng: 76.6450,
    verified: true,
    contactEmail: 'jyotisarupkanya@yahoo.com',
    contactPhone: '+91 160 2281290',
    website: 'https://graceslist.org',
    founded: '1998',
    urgentNeeds: ['College Textbooks & Reference Books', 'Girls Winter Sweaters & Shoes', 'Sanitary & Personal Care Kits'],
    beneficiariesServed: '120 Resident Girls',
    operatingHours: '8:30 AM - 7:00 PM (Everyday)',
    verificationDetails: 'Punjab Women & Child Development Dept #142, 80G Certified',
    impactHighlights: 'Supported 45+ young women through university degrees in nursing, engineering, and teaching.'
  },
  {
    id: 11,
    name: 'All India Pingalwara Charitable Society',
    category: 'oldAgeHome',
    description: 'Founded in 1947 by Bhagat Puran Singh, Pingalwara provides unconditional lifetime shelter, specialized medical wards, and dignified care to over 1,800 destitute, elderly, and infirm individuals across Punjab.',
    address: 'G.T. Road (Head Office, Amritsar) & Village Pamali, Ludhiana Branch',
    city: 'Ludhiana',
    state: 'Punjab',
    lat: 30.8710,
    lng: 75.7600,
    verified: true,
    contactEmail: 'pingalwara57@gmail.com',
    contactPhone: '+91 183 2584713',
    website: 'https://www.pingalwara.org',
    founded: '1947',
    urgentNeeds: ['Bulk Rice, Wheat Flour (Atta) & Dal', 'Adult Diapers & Disinfectants', 'Prosthetic Aids & Wheelchairs'],
    beneficiariesServed: '1,800+ Permanent Inmates',
    operatingHours: '24 Hours Operational',
    verificationDetails: 'Registered Society #130, FCRA Certified, 80G & 10(23C) Tax Exemption',
    impactHighlights: 'Operates special schools, prosthetics workshops, and free multi-bed hospitals caring for the destitute with total compassion.'
  },
  {
    id: 12,
    name: 'SPCA Chandigarh (Society for Prevention of Cruelty to Animals)',
    category: 'ngo',
    description: 'Providing emergency ambulance rescue, veterinary medical surgeries, rehabilitation, and animal shelter for injured, sick, and abandoned animals across Chandigarh Tricity.',
    address: 'Opposite CTU Workshop, Sector 38 (West)',
    city: 'Chandigarh',
    state: 'Chandigarh (UT)',
    lat: 30.7475,
    lng: 76.7380,
    verified: true,
    contactEmail: 'animal@chdut.nic.in',
    contactPhone: '+91 172 2696450',
    website: 'https://chdanimalhusbandry.gov.in',
    founded: '1978',
    urgentNeeds: ['Animal Feed & Dog Kibble Packets', 'Antiseptic Ointments & Bandages', 'Warm Clean Bedding & Towels'],
    beneficiariesServed: '8,000+ Animals Rescued Annually',
    operatingHours: '9:00 AM - 5:00 PM (Emergency 24x7 Ambulance)',
    verificationDetails: 'UT Chandigarh Animal Husbandry Dept Aided Institution, Verified 2026',
    impactHighlights: 'Treats 25-30 rescue animals daily and operates active adoption and Animal Birth Control programs.'
  }
];

export const volunteerActivities = [
  {
    id: 1,
    title: 'Sukhna Lake Eco-Cleanup & Tree Plantation',
    description: 'Join hands with Tricity eco-warriors in cleaning Sukhna Lake walking tracks, planting indigenous tree saplings, and raising plastic-free awareness.',
    type: 'cleanup',
    location: 'Sukhna Lake & Nature Reserve, Sector 1, Chandigarh',
    date: 'Every Sunday Morning',
    spotsAvailable: 25,
    organiser: 'Yuvsatta & Chandigarh Eco-Volunteers'
  },
  {
    id: 2,
    title: 'Weekend Langar & Rations Drive at PGI',
    description: 'Distribute warm nutritional meals, porridge, and clean drinking water to attendant families waiting outside hospital emergency wards.',
    type: 'foodDrive',
    location: 'Outside PGIMER Emergency & GMCH 32, Chandigarh',
    date: 'Every Saturday',
    spotsAvailable: 20,
    organiser: 'Sri Guru Granth Sahib Sewa Society (Tera Hi Tera)'
  },
  {
    id: 3,
    title: 'Winter Warmth Collection & Distribution Camp',
    description: 'Collect, sort, and distribute winter sweaters, jackets, and thermal blankets to underprivileged families in colony settlements before cold waves.',
    type: 'clothingDrive',
    location: 'Sector 17 Plaza & Dhanas Colony, Chandigarh',
    date: '2026-09-18',
    spotsAvailable: 30,
    organiser: 'Tammana NGO'
  },
  {
    id: 4,
    title: 'Weekend Children Tutoring & Math Mentorship',
    description: 'Teach elementary mathematics, English reading, and computer basics to resident children aged 6 to 16, assisting with their school homework.',
    type: 'teaching',
    location: 'Sector 2, Panchkula (Bal Niketan)',
    date: 'Every Saturday & Sunday',
    spotsAvailable: 10,
    organiser: 'Bal Niketan Children Home'
  },
  {
    id: 5,
    title: 'Night Surplus Food Rescue Run',
    description: 'Pick up surplus freshly cooked food from Tricity banquet halls and restaurants, package into hygienic boxes, and distribute to night shelters.',
    type: 'foodDrive',
    location: 'Madhya Marg & Aroma Chowk, Sector 22, Chandigarh',
    date: 'Every Night (8:30 PM - 10:30 PM)',
    spotsAvailable: 15,
    organiser: 'Robin Hood Army (Chandigarh Chapter)'
  },
  {
    id: 6,
    title: 'Elder Companionship & Care Visit',
    description: 'Spend time with senior residents — reading Punjabi and Hindi newspapers, playing carrom or chess, and providing warm conversation.',
    type: 'elderCare',
    location: 'Sector 15-D, Chandigarh',
    date: '2026-09-12',
    spotsAvailable: 12,
    organiser: 'Lions Club Old Age Home'
  },
  {
    id: 7,
    title: 'Pediatric Joy & Story Reading Session',
    description: 'Bring smiles to children in hospital pediatric wards through coloring activities, puppet storytelling, origami, and puzzle games.',
    type: 'teaching',
    location: 'Advanced Pediatric Centre (APC), Sector 12, Chandigarh',
    date: '2026-09-22',
    spotsAvailable: 8,
    organiser: 'Nanhi Jaan (Veeranwali Foundation)'
  },
  {
    id: 8,
    title: 'Tricity Animal Shelter Care & Grooming Drive',
    description: 'Assist veterinary staff in grooming rescued puppies, setting up clean dry bedding, and socializing animals waiting for adoption.',
    type: 'cleanup',
    location: 'SPCA Animal Shelter, Sector 38 West, Chandigarh',
    date: 'Every Sunday',
    spotsAvailable: 14,
    organiser: 'SPCA Chandigarh'
  }
];

export const categoryLabels = { ngo: 'NGO', orphanage: 'Orphanage', oldAgeHome: 'Old Age Home' };
export const donationTypeLabels = { food: 'Food', clothes: 'Clothes', books: 'Books', medicines: 'Medicines', other: 'Other Essentials' };
export const activityTypeLabels = { foodDrive: 'Food Drive', clothingDrive: 'Clothing Drive', teaching: 'Teaching', elderCare: 'Elder Care', cleanup: 'Community Cleanup' };
export const statusLabels = { requested: 'Requested', pickedUp: 'Picked Up', delivered: 'Delivered' };

